In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("AAN.csv")

In [3]:
df.head()

         Date  Open      High       Low     Close     Adj Close   Volume
0  1982-11-04   0.0  1.024691  1.012346  1.012346 -1.263439e+21  9182700
1  1982-11-05   0.0  1.049383  1.024691  1.024691 -1.278846e+21  2370600
2  1982-11-08   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1174500
3  1982-11-09   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1344600
4  1982-11-10   0.0  1.098765  1.074074  1.074074 -1.340476e+21   819400

In [4]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,23.690001,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,23.650000,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,22.549999,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,22.780001,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,19.740000,1421000

In [5]:
df.shape

(9431, 7)

In [6]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9431 entries, 0 to 9430
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9431 non-null   object
 1   Open       9431 non-null   float64
 2   High       9431 non-null   float64
 3   Low        9431 non-null   float64
 4   Close      9431 non-null   float64
 5   Adj Close  9431 non-null   float64
 6   Volume     9431 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 515.9+ KB

In [8]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,9431.000000,9431.000000,9431.000000,9431.000000,9.431000e+03,9.431000e+03
mean,12.692223,12.897235,12.608257,12.753791,-1.851822e+20,2.062132e+05
std,14.571142,14.718309,14.315203,14.516803,5.266073e+20,4.488630e+05
min,0.000000,0.481481,0.481481,0.481481,-2.380501e+21,0.000000e+00
25%,1.444444,1.518519,1.481481,1.481481,-6.826386e+00,6.000000e+02
50%,5.314815,5.333333,5.296296,5.333333,1.307105e+01,1.080000e+04
75%,19.490000,19.955000,19.275000,19.575000,2.921181e+01,3.077000e+05
max,77.989998,78.650002,77.050003,78.139999,1.883516e+19,1.345100e+07

In [9]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [10]:
numeric_cols = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]

(df[numeric_cols] == 0).sum()

Open          450
High            0
Low             0
Close           0
Adj Close       0
Volume       1710
dtype: int64

In [11]:
(df[numeric_cols] < 0).sum()

Open            0
High            0
Low             0
Close           0
Adj Close    2584
Volume          0
dtype: int64

In [12]:
(df["Adj Close"] < 0)

0        True
1        True
2        True
3        True
4        True
        ...
9426    False
9427    False
9428    False
9429    False
9430    False
Name: Adj Close, Length: 9431, dtype: bool

In [13]:
invalid_high = df[(df["High"] < df["Open"]) | (df["High"] < df["Close"])]

In [14]:
invalid_low = df[(df["Low"] > df["Open"]) | (df["Low"] > df["Close"])]

In [15]:
print("Invalid High records:", len(invalid_high))
print("Invalid Low records:", len(invalid_low))

Invalid High records: 0
Invalid Low records: 450

In [16]:
df["Date"] = pd.to_datetime(df["Date"])

In [17]:
df["Date"]

0      1982-11-04
1      1982-11-05
2      1982-11-08
3      1982-11-09
4      1982-11-10
          ...
9426   2020-03-26
9427   2020-03-27
9428   2020-03-30
9429   2020-03-31
9430   2020-04-01
Name: Date, Length: 9431, dtype: datetime64[ns]

In [18]:
print("Duplicate dates:", df["Date"].duplicated().sum())
print("Minimum date:", df["Date"].min())
print("Maximum date:", df["Date"].max())

Duplicate dates: 0
Minimum date: 1982-11-04 00:00:00
Maximum date: 2020-04-01 00:00:00

In [19]:
df["Adj Close"].describe()

count    9.431000e+03
mean    -1.851822e+20
std      5.266073e+20
min     -2.380501e+21
25%     -6.826386e+00
50%      1.307105e+01
75%      2.921181e+01
max      1.883516e+19
Name: Adj Close, dtype: float64

In [20]:
df.nlargest(10, "Adj Close")[["Date", "Adj Close"]]

           Date     Adj Close
1090 1987-02-27  1.883516e+19
1097 1987-03-10  1.883516e+19
1098 1987-03-11  1.883516e+19
1099 1987-03-12  1.883516e+19
1102 1987-03-17  1.883516e+19
1103 1987-03-18  1.883516e+19
1104 1987-03-19  1.883516e+19
1108 1987-03-25  1.883516e+19
1110 1987-03-27  1.870061e+19
1109 1987-03-26  1.843155e+19

In [21]:
df.nsmallest(10, "Adj Close")[["Date","Adj Close"]]

          Date     Adj Close
159 1983-06-22 -2.380501e+21
157 1983-06-20 -2.357390e+21
158 1983-06-21 -2.357390e+21
160 1983-06-23 -2.357390e+21
161 1983-06-24 -2.357390e+21
162 1983-06-27 -2.357390e+21
163 1983-06-28 -2.357390e+21
164 1983-06-29 -2.264945e+21
165 1983-06-30 -2.264945e+21
166 1983-07-01 -2.264945e+21

In [22]:
df.dropna()

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [23]:
df.drop_duplicates()

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [24]:
clean_df = df.copy()

In [25]:
clean_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [26]:
clean_df.shape

(9431, 7)

In [27]:
clean_df = clean_df.drop_duplicates()

In [28]:
clean_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [29]:
clean_df.duplicated().sum()

np.int64(0)

In [30]:
clean_df["Date"] = pd.to_datetime(clean_df["Date"])

In [31]:
clean_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [32]:
clean_df = clean_df.sort_values("Date")

In [33]:
clean_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1982-11-04,0.000000,1.024691,1.012346,1.012346,-1.263439e+21,9182700
1,1982-11-05,0.000000,1.049383,1.024691,1.024691,-1.278846e+21,2370600
2,1982-11-08,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1174500
3,1982-11-09,0.000000,1.061728,1.037037,1.037037,-1.294253e+21,1344600
4,1982-11-10,0.000000,1.098765,1.074074,1.074074,-1.340476e+21,819400
...,...,...,...,...,...,...,...
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,2.369000e+01,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,2.365000e+01,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,2.255000e+01,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,2.278000e+01,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,1.974000e+01,1421000

In [34]:
clean_df = clean_df.reset_index(drop=True)

In [35]:
clean_df.head()

        Date  Open      High       Low     Close     Adj Close   Volume
0 1982-11-04   0.0  1.024691  1.012346  1.012346 -1.263439e+21  9182700
1 1982-11-05   0.0  1.049383  1.024691  1.024691 -1.278846e+21  2370600
2 1982-11-08   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1174500
3 1982-11-09   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1344600
4 1982-11-10   0.0  1.098765  1.074074  1.074074 -1.340476e+21   819400

In [40]:
price_columns = ["Open", "High", "Low", "Close"]

zero_price_row = clean_df[(clean_df[price_columns] == 0).any(axis=True)]

In [41]:
zero_price_row

          Date  Open      High       Low     Close     Adj Close   Volume
0   1982-11-04   0.0  1.024691  1.012346  1.012346 -1.263439e+21  9182700
1   1982-11-05   0.0  1.049383  1.024691  1.024691 -1.278846e+21  2370600
2   1982-11-08   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1174500
3   1982-11-09   0.0  1.061728  1.037037  1.037037 -1.294253e+21  1344600
4   1982-11-10   0.0  1.098765  1.074074  1.074074 -1.340476e+21   819400
..         ...   ...       ...       ...       ...           ...      ...
459 1984-08-28   0.0  1.314815  1.296296  1.314815 -1.640928e+21    47200
462 1984-08-31   0.0  1.314815  1.259259  1.277778 -1.594705e+21    24300
463 1984-09-04   0.0  1.259259  1.259259  1.259259 -1.571594e+21     6700
464 1984-09-05   0.0  1.314815  1.222222  1.240741 -1.548482e+21    48600
465 1984-09-06   0.0  1.222222  1.222222  1.222222 -1.525370e+21    10800

[450 rows x 7 columns]

In [43]:
len(zero_price_row)

450

In [46]:
clean_df[price_columns] = clean_df[price_columns].replace(0, np.nan)

In [47]:
clean_df[price_columns].isnull().sum()

Open     450
High       0
Low        0
Close      0
dtype: int64

In [48]:
clean_df[price_columns] = clean_df[price_columns].interpolate(
    method="linear"
)

In [49]:
clean_df[price_columns].isnull().sum()

Open     184
High       0
Low        0
Close      0
dtype: int64

In [50]:
clean_df[clean_df[price_columns].isnull().any(axis=1)]

          Date  Open      High       Low     Close     Adj Close   Volume
0   1982-11-04   NaN  1.024691  1.012346  1.012346 -1.263439e+21  9182700
1   1982-11-05   NaN  1.049383  1.024691  1.024691 -1.278846e+21  2370600
2   1982-11-08   NaN  1.061728  1.037037  1.037037 -1.294253e+21  1174500
3   1982-11-09   NaN  1.061728  1.037037  1.037037 -1.294253e+21  1344600
4   1982-11-10   NaN  1.098765  1.074074  1.074074 -1.340476e+21   819400
..         ...   ...       ...       ...       ...           ...      ...
179 1983-07-21   NaN  1.740741  1.666667  1.666667 -2.080049e+21   301000
180 1983-07-22   NaN  1.777778  1.685185  1.685185 -2.103163e+21    12100
181 1983-07-25   NaN  1.777778  1.703704  1.703704 -2.126273e+21    98500
182 1983-07-26   NaN  1.777778  1.685185  1.685185 -2.103163e+21   214600
183 1983-07-27   NaN  1.740741  1.666667  1.666667 -2.080049e+21   156600

[184 rows x 7 columns]

In [51]:
(clean_df[price_columns] == 0).sum()

Open     0
High     0
Low      0
Close    0
dtype: int64

In [52]:
invalid_ohlc = (
    (clean_df["High"] < clean_df["Open"]) |
    (clean_df["High"] < clean_df["Close"]) |
    (clean_df["Low"] > clean_df["Open"]) |
    (clean_df["Low"] > clean_df["Close"])
)

In [53]:
invalid_ohlc.sum()

np.int64(210)

In [54]:
clean_df[invalid_ohlc]

          Date      Open      High       Low     Close     Adj Close  Volume
186 1983-08-01  1.650794  1.629630  1.537037  1.537037 -1.918268e+21   29700
187 1983-08-02  1.642857  1.629630  1.537037  1.537037 -1.918268e+21   52600
188 1983-08-03  1.634921  1.592593  1.500000  1.500000 -1.872045e+21   33700
189 1983-08-04  1.626984  1.592593  1.500000  1.500000 -1.872045e+21   12100
190 1983-08-05  1.619048  1.574074  1.481481  1.481481 -1.848933e+21   41800
..         ...       ...       ...       ...       ...           ...     ...
456 1984-08-23  1.305996  1.305556  1.296296  1.305556 -1.629373e+21   47200
457 1984-08-24  1.308201  1.305556  1.277778  1.305556 -1.629373e+21   35100
458 1984-08-27  1.310406  1.277778  1.268519  1.268519 -1.583149e+21   20200
463 1984-09-04  1.277778  1.259259  1.259259  1.259259 -1.571594e+21    6700
465 1984-09-06  1.240741  1.222222  1.222222  1.222222 -1.525370e+21   10800

[210 rows x 7 columns]

In [56]:
(clean_df["Volume"] < 0).sum()

np.int64(0)

In [57]:
clean_df[clean_df["Volume"] < 0]

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume]
Index: []

In [58]:
clean_df["Adj Close"].describe()

count    9.431000e+03
mean    -1.851822e+20
std      5.266073e+20
min     -2.380501e+21
25%     -6.826386e+00
50%      1.307105e+01
75%      2.921181e+01
max      1.883516e+19
Name: Adj Close, dtype: float64

In [59]:
clean_df[
    clean_df["Adj Close"] <= 0
][["Date", "Close", "Adj Close"]]

           Date     Close     Adj Close
0    1982-11-04  1.012346 -1.263439e+21
1    1982-11-05  1.024691 -1.278846e+21
2    1982-11-08  1.037037 -1.294253e+21
3    1982-11-09  1.037037 -1.294253e+21
4    1982-11-10  1.074074 -1.340476e+21
...         ...       ...           ...
4088 1999-01-07  4.444445 -4.981695e+00
4089 1999-01-08  4.444445 -4.981695e+00
4090 1999-01-11  4.333333 -4.857155e+00
4091 1999-01-12  4.333333 -4.857155e+00
4092 1999-01-13  4.333333 -4.857155e+00

[2584 rows x 3 columns]

In [60]:
clean_df[
    ["Close", "Adj Close"]
].describe()

             Close     Adj Close
count  9431.000000  9.431000e+03
mean     12.753791 -1.851822e+20
std      14.516803  5.266073e+20
min       0.481481 -2.380501e+21
25%       1.481481 -6.826386e+00
50%       5.333333  1.307105e+01
75%      19.575000  2.921181e+01
max      78.139999  1.883516e+19

In [61]:
clean_df.isnull().sum()

Date           0
Open         184
High           0
Low            0
Close          0
Adj Close      0
Volume         0
dtype: int64

In [62]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9431 entries, 0 to 9430
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9431 non-null   datetime64[ns]
 1   Open       9247 non-null   float64
 2   High       9431 non-null   float64
 3   Low        9431 non-null   float64
 4   Close      9431 non-null   float64
 5   Adj Close  9431 non-null   float64
 6   Volume     9431 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 515.9 KB

In [63]:
clean_df.duplicated().sum()

np.int64(0)

In [64]:
clean_df.head()

        Date  Open      High       Low     Close     Adj Close   Volume
0 1982-11-04   NaN  1.024691  1.012346  1.012346 -1.263439e+21  9182700
1 1982-11-05   NaN  1.049383  1.024691  1.024691 -1.278846e+21  2370600
2 1982-11-08   NaN  1.061728  1.037037  1.037037 -1.294253e+21  1174500
3 1982-11-09   NaN  1.061728  1.037037  1.037037 -1.294253e+21  1344600
4 1982-11-10   NaN  1.098765  1.074074  1.074074 -1.340476e+21   819400

In [65]:
clean_df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,23.690001,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,23.650000,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,22.549999,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,22.780001,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,19.740000,1421000

In [66]:
clean_df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
9426,2020-03-26,24.400000,25.680000,23.250000,23.690001,23.690001,1395600
9427,2020-03-27,22.330000,24.260000,21.820000,23.650000,23.650000,1282600
9428,2020-03-30,23.260000,23.540001,21.350000,22.549999,22.549999,1213500
9429,2020-03-31,22.450001,23.639999,22.209999,22.780001,22.780001,1551500
9430,2020-04-01,21.549999,21.969999,19.650000,19.740000,19.740000,1421000

In [67]:
clean_df.info

<bound method DataFrame.info of            Date       Open       High        Low      Close     Adj Close  \
0    1982-11-04        NaN   1.024691   1.012346   1.012346 -1.263439e+21
1    1982-11-05        NaN   1.049383   1.024691   1.024691 -1.278846e+21
2    1982-11-08        NaN   1.061728   1.037037   1.037037 -1.294253e+21
3    1982-11-09        NaN   1.061728   1.037037   1.037037 -1.294253e+21
4    1982-11-10        NaN   1.098765   1.074074   1.074074 -1.340476e+21
...         ...        ...        ...        ...        ...           ...
9426 2020-03-26  24.400000  25.680000  23.250000  23.690001  2.369000e+01
9427 2020-03-27  22.330000  24.260000  21.820000  23.650000  2.365000e+01
9428 2020-03-30  23.260000  23.540001  21.350000  22.549999  2.255000e+01
9429 2020-03-31  22.450001  23.639999  22.209999  22.780001  2.278000e+01
9430 2020-04-01  21.549999  21.969999  19.650000  19.740000  1.974000e+01

       Volume
0     9182700
1     2370600
2     1174500
3     1344600
4      819400
...       ...
9426  1395600
9427  1282600
9428  1213500
9429  1551500
9430  1421000

[9431 rows x 7 columns]>

In [68]:
clean_df.describe()

,Date,Open,High,Low,Close,Adj Close,Volume
count,9431,9247.000000,9431.000000,9431.000000,9431.000000,9.431000e+03,9.431000e+03
mean,2001-07-11 04:12:41.912840576,12.980745,12.897235,12.608257,12.753791,-1.851822e+20,2.062132e+05
min,1982-11-04 00:00:00,0.481481,0.481481,0.481481,0.481481,-2.380501e+21,0.000000e+00
25%,1992-03-03 12:00:00,1.555556,1.518519,1.481481,1.481481,-6.826386e+00,6.000000e+02
50%,2001-07-03 00:00:00,5.629630,5.333333,5.296296,5.333333,1.307105e+01,1.080000e+04
75%,2010-11-16 12:00:00,20.360001,19.955000,19.275000,19.575000,2.921181e+01,3.077000e+05
max,2020-04-01 00:00:00,77.989998,78.650002,77.050003,78.139999,1.883516e+19,1.345100e+07
std,NaN,14.573491,14.718309,14.315203,14.516803,5.266073e+20,4.488630e+05

In [69]:
clean_df.shape

(9431, 7)