In [1]:
import pandas as pd

In [2]:
a = {
    "Name": ["Alice", "Bob", "charlie","David", "Emma"],
    "Age" : [25,30,35,40,22],
    "Score": [88,92,79,85,95]
}

In [3]:
df = pd.DataFrame(a)

In [5]:
print(df)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  charlie   35     79
3    David   40     85
4     Emma   22     95

In [4]:
print(df.tail(2))

    Name  Age  Score
3  David   40     85
4   Emma   22     95

In [12]:
print(df.head(3))

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  charlie   35     79

In [13]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes
None

In [14]:
print(df.shape)

(5, 3)

In [18]:
print(df.dtypes)

Name       str
Age      int64
Score    int64
dtype: object

In [25]:
df["Name"]

0      Alice
1        Bob
2    charlie
3      David
4       Emma
Name: Name, dtype: str

In [23]:
df[["Name","Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  charlie   35
3    David   40
4     Emma   22

In [28]:
df.loc[0,"Score"]

np.int64(88)

In [5]:
df.loc[1:3,["Name","Age"]]

      Name  Age
1      Bob   30
2  charlie   35
3    David   40

In [6]:
df.iloc[0]

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [9]:
df.values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

In [17]:
df.rename(columns={"Score":"Marks"},inplace = True)
df.set_index("Name", inplace = True)

In [20]:
df.reset_index(inplace = True)
df

   index     Name  Age  Marks
0      0    Alice   25     88
1      1      Bob   30     92
2      2  charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

In [21]:
data =  {
    "Name": ["Alice", "Bob", "charlie","David", "Emma"],
    "Age" : [25,30,35,40,22],
    "Score": [88,92,79,85,95]
}

In [22]:
new_data = pd.DataFrame(data)
new_data

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  charlie   35     79
3    David   40     85
4     Emma   22     95

In [23]:
new_data.tail(2)

    Name  Age  Score
3  David   40     85
4   Emma   22     95

In [24]:
new_data.head(3)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  charlie   35     79

In [26]:
new_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [27]:
sub_data = new_data[["Name","Age"]]
sub_data

      Name  Age
0    Alice   25
1      Bob   30
2  charlie   35
3    David   40
4     Emma   22

In [28]:
new_data.shape

(5, 3)