In [2]:
import pandas as pd

In [20]:
data = {
    "Product": ["Pen","Notebook", "Pencil","Marker","Eraser","Sharpener"],
    "Price":[10,50,5,30,8,12],
    "Stock":[100,60,200,80,150,120],
    "Rating":[4.5,4.7,4.2,4.8,4.3,4.4]
}

In [21]:
df = pd.DataFrame(data)

In [22]:
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [23]:
df.sort_values(by="Price",ascending=False)

     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [7]:
df.sort_values(by = ["Price","Stock"],ascending = [True, False])

        Name  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

In [24]:
df.mean(numeric_only=True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [25]:
df.median(numeric_only=True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [26]:
df.mode(numeric_only=True)

   Price  Stock  Rating
0      5     60     4.2
1      8     80     4.3
2     10    100     4.4
3     12    120     4.5
4     30    150     4.7
5     50    200     4.8

In [27]:
df.std(numeric_only=True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [28]:
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

In [29]:
df["Product"].value_counts()

Product
Pen          1
Notebook     1
Pencil       1
Marker       1
Eraser       1
Sharpener    1
Name: count, dtype: int64

In [30]:
df["Product"].value_counts(normalize=True)

Product
Pen          0.166667
Notebook     0.166667
Pencil       0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

In [32]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [33]:
df.cov(numeric_only=True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [35]:
df["Price"].corr(df["Rating"])

np.float64(0.8204016469535791)