In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None , 35 , 40 , None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"], 
    "Score": [85,91,np.nan,88,95],
}

In [3]:
df = pd.DataFrame(data)
df

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0        NaN    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [4]:
df.isnull()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [5]:
df.isnull().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [6]:
df.dropna()

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["City"] = df["City"].fillna(df["City"].mode())
df["Score"] = df["Score"].fillna(0)

In [8]:
df

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [13]:
a = {
   "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30 , 35 , 40 , 22], 
    "Score": [85,91,79,88,95],
}

df = pd.DataFrame(a)

In [14]:
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     91
2  Charlie   35     79
3    David   40     88
4     Emma   22     95

In [12]:
df["Score"] = df["Score"].astype(float)

In [15]:
c = df.copy()

In [16]:
c

      Name  Age  Score
0    Alice   25     85
1      Bob   30     91
2  Charlie   35     79
3    David   40     88
4     Emma   22     95

In [17]:
c["Name"] = c["Name"].replace("Bob","Robert")

In [18]:
c

      Name  Age  Score
0    Alice   25     85
1   Robert   30     91
2  Charlie   35     79
3    David   40     88
4     Emma   22     95

In [20]:
c["Score"] = c["Score"].replace({88.0:90.0,95.0:99.0})
c

      Name  Age  Score
0    Alice   25     85
1   Robert   30     91
2  Charlie   35     79
3    David   40     90
4     Emma   22     99

In [21]:
c.drop(["Age"],axis = True)

      Name  Score
0    Alice     85
1   Robert     91
2  Charlie     79
3    David     90
4     Emma     99

In [22]:
c.drop([0,2],axis = 0)

     Name  Age  Score
1  Robert   30     91
3   David   40     90
4    Emma   22     99

In [28]:
data =  {
   "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Devic"],
    "Age": [25, 30 , 35 , 25 , 30, 40], 
    "Score": [85,92,79,85,92, 85],
}
df = pd.DataFrame(data)

In [24]:
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    Devic   40     85

In [29]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [30]:
df.drop_duplicates()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     92
2  Charlie   35     79
5    Devic   40     85