In [1]:
import pandas as pd

In [2]:
# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})

# Dataset 2: More products (same columns as df1)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})

# Dataset 3: Additional info (different columns)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})

In [4]:
pd.concat([df1,df2],ignore_index=True)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [5]:
pd.concat([df1,df3])

   ProductID ProductName  Price  Stock  Rating
0      101.0         Pen   10.0    NaN     NaN
1      102.0    Notebook   50.0    NaN     NaN
2      103.0      Marker   30.0    NaN     NaN
0        NaN         NaN    NaN  100.0     4.5
1        NaN         NaN    NaN   60.0     4.7
2        NaN         NaN    NaN   80.0     4.8

In [8]:
pd.concat([df1,df3],axis = True,ignore_index = False)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

In [9]:
products = pd.concat([df1,df2],ignore_index=False)

In [10]:
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [11]:
sales = pd.DataFrame({
    "ProductID": [101,102,104,106],
    "UnitsSold": [500,200,150,50]
})

In [13]:
pd.merge(products,sales, on = "ProductID")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [14]:
pd.merge(products,sales, on = "ProductID", how = "inner")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

In [15]:
pd.merge(products,sales, on = "ProductID", how = "left")

   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      8        NaN

In [16]:
pd.merge(products,sales, on = "ProductID", how = "right")

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50

In [17]:
pd.merge(products,sales, on = "ProductID", how = "outer")

   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

In [18]:
products = pd.concat([df1,df2],ignore_index=False)

In [19]:
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [20]:
stock = pd.DataFrame({
    "Stock":[100,60,80,120,150],
}, index = [101,102,103,104,105])

In [24]:
p_dataSet = products.set_index("ProductID")

In [25]:
p_dataSet.join(stock)

          ProductName  Price  Stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150

In [26]:
# Sales data
sales = pd.DataFrame({
    "ProductID": [201, 202, 203, 204],
    "UnitsSold": [500, 300, 400, 250]
})

# Revenue data (missing ProductID 204, extra 205)
revenue = pd.DataFrame({
    "ProductID": [201, 202, 203, 205],
    "Revenue": [7500, 4500, 6800, 1200]
})

In [29]:
merged_df = pd.merge(sales,revenue,on="ProductID",how="outer")
merged_df

   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0

In [30]:
pd.merge(sales,revenue,on="ProductID",how="left")

   ProductID  UnitsSold  Revenue
0        201        500   7500.0
1        202        300   4500.0
2        203        400   6800.0
3        204        250      NaN

In [31]:
pd.merge(sales,revenue,on="ProductID",how="right")

   ProductID  UnitsSold  Revenue
0        201      500.0     7500
1        202      300.0     4500
2        203      400.0     6800
3        205        NaN     1200

In [32]:
pd.merge(sales,revenue,on="ProductID",how="inner")

   ProductID  UnitsSold  Revenue
0        201        500     7500
1        202        300     4500
2        203        400     6800