In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = {
    "Name": ["Alic","Bob","Charlie","David","Emma"],
    "Age": [25,30,35,40,22],
    "Score": [88,92,79,85,95]
}
df = pd.DataFrame(data)

In [3]:
df

      Name  Age  Score
0     Alic   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [5]:
df[df["Age"] > 30 ]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [8]:
df[(df["Age"] > 25) & (df["Score"] > 85)]

  Name  Age  Score
1  Bob   30     92

In [9]:
df[(df["Age"] < 25 ) | (df["Score"] > 90)]

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

In [10]:
df[~(df["Score"] > 85)]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [11]:
df[(df["Age"] > 25) & (df["Score"] > 85)]

  Name  Age  Score
1  Bob   30     92

In [12]:
df.query("Age > 25")

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85

In [13]:
df.query("Age < 35 and Score >= 85")

   Name  Age  Score
0  Alic   25     88
1   Bob   30     92
4  Emma   22     95

In [14]:
hold = 90
df.query("Score > @hold")

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

In [16]:
df["Name"].str.lower()

0       alic
1        bob
2    charlie
3      david
4       emma
Name: Name, dtype: str