In [1]:
import pandas as pd

In [6]:
data = {
    "Employee": ["John", "Sarah", "Mick", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mick         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [10]:
df["Department"].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [15]:
# df[df["Department"] == "IT"]["Salary"].mean()

df.groupby("Department")["Salary"].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [16]:
df.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [17]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

                    mean    max    min
Department
Finance     61000.000000  65000  58000
HR          51000.000000  52000  50000
IT          72333.333333  75000  70000

In [18]:
data = {
    "Employee": ["John", "Sarah", "Mick", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age":[20,32,30,27,35,29,31,26]
}

df = pd.DataFrame(data)

In [19]:
df

  Employee Department  Salary  Age
0     John         HR   50000   20
1    Sarah         IT   70000   32
2     Mick         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [21]:
df.groupby("Department").agg({
    "Salary":["mean","max","min"],
    "Age":["mean","max"],
})

                  Salary                      Age
                    mean    max    min       mean max
Department
Finance     61000.000000  65000  58000  29.333333  35
HR          51000.000000  52000  50000  24.500000  29
IT          72333.333333  75000  70000  31.000000  32

In [24]:
df.pivot_table(values=["Salary","Age"],index="Department",aggfunc="mean")

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          24.500000  51000.000000
IT          31.000000  72333.333333

In [26]:
df["AgeGroup"] = pd.cut(df["Age"],bins = [25,30,35,40],labels=["25-30","31-35","36-40"])

In [27]:
df

  Employee Department  Salary  Age AgeGroup
0     John         HR   50000   20      NaN
1    Sarah         IT   70000   32    31-35
2     Mick         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [29]:
pd.crosstab(df["Department"],df["AgeGroup"])

AgeGroup    25-30  31-35
Department
Finance         2      1
HR              1      0
IT              1      2