In [2]:
import pandas as pd 
import numpy as np

In [4]:
data = {
    "Name":["Alice","Bob","Charlie","David","Emma"],
    "Math":[88,75,92,60,85],
    "Science":[90,80,78,70,95]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

      Name  Math  Science
0    Alice    88       90
1      Bob    75       80
2  Charlie    92       78
3    David    60       70
4     Emma    85       95

In [11]:
df["Total_Marks"] = df[["Math","Science"]].apply(lambda row : row.sum(),axis=True)

In [12]:
df

      Name  Math  Science  Total_Marks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [13]:
col_mean = df[["Math","Science"]].apply(lambda col : col.mean())

In [14]:
col_mean

Math       80.0
Science    82.6
dtype: float64

In [16]:
def to_gread(Score): 
    if Score >= 90: 
        return "A"
    elif Score >= 80: 
        return "B"
    elif Score >= 70: 
        return "C" 
    elif Score >= 40: 
        return "D"
    else: 
        return "Fail" 

df["Maths Gread"] = df["Math"].apply(to_gread)

In [17]:
df

      Name  Math  Science  Total_Marks Maths Gread
0    Alice    88       90          178           B
1      Bob    75       80          155           C
2  Charlie    92       78          170           A
3    David    60       70          130           D
4     Emma    85       95          180           B

In [18]:
df["Name"] = df["Name"].map(str.lower)

In [19]:
df

      Name  Math  Science  Total_Marks Maths Gread
0    alice    88       90          178           B
1      bob    75       80          155           C
2  charlie    92       78          170           A
3    david    60       70          130           D
4     emma    85       95          180           B

In [20]:
df["Bouns Math"] = df["Math"].map(lambda x: x + 5)

In [21]:
df

      Name  Math  Science  Total_Marks Maths Gread  Bouns Math
0    alice    88       90          178           B          93
1      bob    75       80          155           C          80
2  charlie    92       78          170           A          97
3    david    60       70          130           D          65
4     emma    85       95          180           B          90